### ISSUE TITLE
How to modify Label CSS

### ISSUE THREAD

**Issue by keanedawg** [offirgolan/ember-bootstrap-floating-labels#3]
So currently our floating label looks like this

![image](https://user-images.githubusercontent.com/14279577/29289895-d9c11fbe-8103-11e7-8581-6b296f683ce9.png)

The animation is great. The only problem is that we would like to modify certain properties like font-family, color, and most importantly position.

Is there a way to do this?

**Comment by keanedawg** [comment]
Well, it turned out that this was a formLayout issue. 

formLayout has to be horizontal or inline for the position to be fixed. Other CSS such as color or font-family I'm still not necessarily sure about.

**Comment by offirgolan** [comment]
@keanedawg these are [all the styles](https://github.com/offirgolan/ember-bootstrap-floating-labels/blob/master/addon/styles/addon.css) that are being applied by default. You can overwrite them in your app's CSS by targeting `.floating-label`

**Comment by keanedawg** [comment]
Thank you @offirgolan! This is what we needed
